APP_SECRET: "aklsjdfoinnozxcnvnoqanfwenfoasd"
DATABASE_PRODUCTION: 'congress'
DATABASE_TEST: 'congress_test'
DATABASE_HOST: 'localhost'
DATABASE_USERNAME: 'root'
DATABASE_PASSWORD: ''
MAILGUN_SMTP_PORT: '587'
MAILGUN_SMTP_SERVER: 'smtp.mailgun.org'
MAILGUN_SMTP_LOGIN: 'postmaster@app944162fa46b64929acf2db92a12dd382.mailgun.org'
MAILGUN_SMTP_PASSWORD: 'ca92f044f471b5d807e978dd20303d82'
MAILGUN_HOST: 'smtp.mailgun.org'
SITE_DOMAIN: 'coloneldeantocongress.herokuapp.com'
EMAIL: 'admin@coloneldeantocongress.org'
ADMIN_EMAIL: 'mike.hoffert@gmail.com'