APP_SECRET: "aklsjdfoinnozxcnvnoqanfwenfoasd"
DATABASE_ADAPTER: 'mysql2'
DATABASE_ENCODING: 'utf8'
DATABASE_PRODUCTION: 'congress'
DATABASE_TEST: 'congress_test'
DATABASE_POOL: '5'
DATABASE_HOST: 'localhost'
DATABASE_USERNAME: 'root'
DATABASE_PASSWORD: ''