menubar: false
statusbar: false
height: 500
fontsize_formats: "10px 12px 14px 16px 24px"
theme_advanced_fonts: "Cinzel, serif;Open Sans;"
toolbar:
  - bold italic forecolor backcolor fontsizeselect | link | alignleft aligncenter alignright | bullist numlist | undo redo | removeformat
plugins:
  - link
  - textcolor